# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('codigo_act', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nombr_acti', models.CharField(max_length=150)),
                ('descripcio', models.TextField(max_length=500)),
                ('fecha_inic', models.DateField()),
                ('fecha_fina', models.DateField()),
            ],
        ),
    ]
