# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombr_acti', models.CharField(max_length=150, verbose_name='Nombre De La Actividad')),
                ('descripcio', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('fecha_inic', models.DateField(blank=True, null=True, verbose_name='Fecha De Inicio')),
                ('hora_inico', models.TimeField(verbose_name='Hora De Inicio')),
                ('hora_final', models.TimeField(verbose_name='Hora De Culminacion')),
                ('fecha_fina', models.DateField(blank=True, null=True, verbose_name='Fecha De Culminacion')),
                ('status1', models.BooleanField(default=False)),
                ('status2', models.BooleanField(default=False)),
                ('status3', models.BooleanField(default=False)),
            ],
        ),
    ]
