# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_entrega', models.CharField(max_length=10)),
                ('fecha_retiro', models.CharField(blank=True, max_length=10, null=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Alumno', to='alumno.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('nombr_instr', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumento.Instrumento'),
        ),
    ]
