# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='id',
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='disponibles',
            field=models.IntegerField(default=0, verbose_name='Disponibles'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='nombr_instr',
            field=models.CharField(choices=[('Programa Alma Llanera', 'Programa Alma Llanera'), ('Arpa Clasica', 'Arpa Clasica'), ('Orquesta Infantil', 'Orquesta Infantil'), ('Oboe', 'Oboe'), ('Cuatro', 'Cuatro'), ('Percusion', 'Percusion'), ('Violincello', 'Violincello'), ('Trombon', 'Trombon'), ('Coro/Lenguaje Musical', 'Coro/Lenguaje Musical'), ('Flauta/Lenguaje Musical', 'Flauta/Lenguaje Musical'), ('Corno', 'Corno'), ('Guitarra', 'Guitarra'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Viola/Lenguaje Musical', 'Viola/Lenguaje Musical'), ('Flauta', 'Flauta'), ('Clarinete', 'Clarinete'), ('Tuba', 'Tuba'), ('Trompeta/Lenguaje Musical', 'Trompeta/Lenguaje Musical'), ('Contrabajo', 'Contrabajo'), ('Pianista', 'Pianista')], max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='stock_max',
            field=models.IntegerField(default=0, verbose_name='Cantidad Maxima'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='stock_min',
            field=models.IntegerField(default=1, verbose_name='Cantidad Minima'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='uso',
            field=models.IntegerField(default=0, verbose_name='Uso'),
        ),
    ]
