# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='id',
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='nombr_instr',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Nombre'),
        ),
    ]
