# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_auto_20180310_1002'),
        ('instrumento', '0003_auto_20180310_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_entrega', models.CharField(max_length=10)),
                ('fecha_retiro', models.CharField(blank=True, max_length=10, null=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumento.Instrumento')),
            ],
        ),
    ]
