# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0004_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Alumno', to='alumno.Alumno'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
