# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nacionalidad', models.CharField(choices=[('V', 'V'), ('E', 'E')], default=2, max_length=5)),
                ('cedula_alumno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('sexo_alumno', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=2, max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entid_feder', models.CharField(choices=[('Distrito Capital', 'Distrito Capital'), ('Miranda', 'Miranda'), ('Aragua', 'Aragua'), ('Monagas', 'Monagas'), ('Falcon', 'Falcon'), ('Carabobo', 'Carabobo'), ('Nueva Esparta', 'Nueva Esparta'), ('Anzoategui', 'Anzoategui'), ('Vargas', 'Vargas'), ('Zulia', 'Zulia'), ('Bolivar', 'Bolivar'), ('Lara', 'Lara'), ('Merida', 'Merida'), ('Tachira', 'Tachira'), ('Guarico', 'Guarico'), ('Cojedes', 'Cojedes'), ('Trujillo', 'Trujillo'), ('Barinas', 'Barinas'), ('Sucre', 'Sucre'), ('Yaracuy', 'Yaracuy'), ('Portuguesa', 'Portuguesa'), ('Delta Amacuro', 'Delta Amacuro'), ('Apure', 'Apure'), ('Amazonas', 'Amazonas')], default=0, max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('parroquia', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('barri_urban', models.CharField(max_length=250)),
                ('calle_avend', models.CharField(max_length=150)),
                ('apt_casa', models.CharField(max_length=100)),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Educa_Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_uno', models.BooleanField(default=False, verbose_name='Nivel I')),
                ('nivel_dos', models.BooleanField(default=False, verbose_name='Nivel II')),
                ('nivel_tres', models.BooleanField(default=False, verbose_name='Nivel III')),
                ('nivel_cuar', models.BooleanField(default=False, verbose_name='Nivel IV')),
                ('primer_grado', models.BooleanField(default=False, verbose_name='Primer Grado')),
                ('segundo_grado', models.BooleanField(default=False, verbose_name='Primer Grado')),
                ('tercer_grado', models.BooleanField(default=False, verbose_name='Segundo Grado')),
                ('cuarto_grado', models.BooleanField(default=False, verbose_name='Cuarto Grado')),
                ('quinto_grado', models.BooleanField(default=False, verbose_name='Quinto Grado')),
                ('sexto_grado', models.BooleanField(default=False, verbose_name='Sexto Grado')),
                ('educ_med_uno', models.BooleanField(default=False, verbose_name='Media I')),
                ('educ_med_dos', models.BooleanField(default=False, verbose_name='Media II')),
                ('primer', models.BooleanField(default=False, verbose_name='Primer A\xf1o')),
                ('segund', models.BooleanField(default=False, verbose_name='Segundo A\xf1o')),
                ('tercer', models.BooleanField(default=False, verbose_name='Tercer A\xf1o')),
                ('cuarto', models.BooleanField(default=False, verbose_name='Cuarto A\xf1o')),
                ('quinto', models.BooleanField(default=False, verbose_name='Quinto A\xf1o')),
                ('curso', models.CharField(max_length=100)),
                ('cedula_alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Educa_Musi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progama_orque', models.CharField(max_length=100, verbose_name='Programas Orquestales Y/O Corales En Los Que Participa')),
                ('instru_princi', models.CharField(max_length=100, verbose_name='Instrumento Principal')),
                ('instru_secund', models.CharField(max_length=100, verbose_name='Instrumento Secundario')),
                ('prof_clas_ind', models.CharField(max_length=100, verbose_name='Profesor De Clase Individial')),
                ('academ_catedr', models.BooleanField(default=False, verbose_name='El Alumno Recibe Clases En Una Academia O Catedra Nacional?')),
                ('nombr_academi', models.CharField(max_length=100, verbose_name='Escriba El Nombre De La Catedra Nacional En La Cual Cursa Estudios')),
                ('clas_acad_cate', models.CharField(max_length=100, verbose_name='Ha Sido Selecionado(a) Para Pertenecer A Una Orquesta/Coro Nacional?')),
                ('nom_aca_cate', models.CharField(max_length=100, verbose_name='Ha Sido Selecionado(a) Para Pertenecer A Una Orquesta/Coro Regional?')),
                ('inst_espc_mus', models.CharField(max_length=100, verbose_name='Cursa Estudios En Una Institucion Especializada En Musica?')),
                ('bec_est_esp', models.BooleanField(default=False, verbose_name='Recibe Alguna Beca O Ayuda Para Cursar Estudios Especializados En Musica?')),
                ('estu_cur', models.CharField(max_length=100, verbose_name='Que Estudios Cursa?')),
                ('inst_empr_bec', models.CharField(max_length=100, verbose_name='Que Institucion O Empresa Otorga La Beca')),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empre', models.CharField(max_length=150, verbose_name='Nombre De La Empresa')),
                ('nombre_jefe', models.CharField(max_length=100, verbose_name='Jefe De La Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('cedula_familia', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_familia', models.CharField(max_length=50)),
                ('apelli_familia', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('telef_cel', models.IntegerField()),
                ('telef_res', models.IntegerField()),
                ('vive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Percep_nino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_sien_bie', models.BooleanField(default=False, verbose_name='Me Siento Bien')),
                ('m_sien_seg', models.BooleanField(default=False, verbose_name='Me Siento Seguro')),
                ('sien_mejo', models.BooleanField(default=False, verbose_name='Siento Que He Mejorado Como Ser Humano')),
                ('mas_apre_com', models.BooleanField(default=False, verbose_name='Soy Mas Apreciado En La Comunidad')),
                ('m_sien_cap', models.BooleanField(default=False, verbose_name='Me Siento Cansado')),
                ('m_sien_mot', models.BooleanField(default=False, verbose_name='Me Siento Desmotivado')),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Percep_Repre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup_fam_reco_com', models.BooleanField(default=False, verbose_name='Como Grupo Familiar Somos Reconocidos En La Comunidad (Nos Respetan Mas)')),
                ('asis_nin_act_mus', models.BooleanField(default=False, verbose_name='La Asistencia De Mis Ni\xf1os Al La Actividad Musical, Mejoro Las Relaciones Familiares')),
                ('prac_mus_ent_eco', models.BooleanField(default=False, verbose_name='La Practica Musical Produce Una Entrada Economica Mas En El Grupo Familiar')),
                ('viv_mej', models.BooleanField(default=False, verbose_name='Ahora Vivo Mejor')),
                ('otra_razon', models.CharField(max_length=100, verbose_name='Otra Razon')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('cedula_repres', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_repres', models.CharField(max_length=50)),
                ('apelli_repres', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(choices=[(b'', b'---------'), (b'Comerciante', b'Comerciante'), (b'Barbero', b'Barbero'), (b'Estudiante', b'Estudiante'), (b'Empleadoa', b'Empleado(a)'), (b'Jubiladoa', b'Jubilado(a)'), (b'Tecnico', b'Tecnico'), (b'Pensionadoa', b'Pensionado(a)'), (b'Obreroa', b'Obrero(a)'), (b'Educadora', b'Educador(a)'), (b'Pastora', b'Pastor(a)'), (b'Herrero', b'Herrero'), (b'Maternal', b'Maternal'), (b'Soldador', b'Soldador'), (b'Estilita', b'Estilita'), (b'Manicurista', b'Manicurista'), (b'Amao_de_casa', b'Ama(o) de casa'), (b'Nutricionista', b'Nutricionista'), (b'Obreroa_Educacional', b'Obrero(a) Educacional'), (b'Contador', b'Contador'), (b'Cocineroa', b'Cocinero(a)'), (b'Policia', b'Policia'), (b'Administradorar', b'Administrador(ar)'), (b'Promotora_Socia', b'Promotor(a) Social'), (b'Docente', b'Docente'), (b'Custodio', b'Custodio'), (b'Pencionadoa', b'Pencionado(a)'), (b'Mecanico', b'Mecanico'), (b'Abogadoa', b'Abogado(a)'), (b'Chofer', b'Chofer'), (b'Empleadoa_Publico', b'Empleado(a) Publico'), (b'Laboratorista', b'Laboratorista'), (b'Peluqueroa', b'Peluquero(a)'), (b'Educadora', b'Educador(a)'), (b'Agricultora', b'Agricultor(a)'), (b'TSU', b'TSU'), (b'Enfermeroa', b'Enfermero(a)'), (b'Carpinteroa', b'Carpintero(a)'), (b'Ambientalista', b'Ambientalista'), (b'Militar', b'Militar'), (b'Albanil', b'Alba\xc3\xb1il'), (b'Secretariao', b'Secretaria(o)'), (b'Deportista', b'Deportista'), (b'Vigilante', b'Vigilante'), (b'Costurera', b'Costurera'), (b'Discapacidad', b'Discapacidad'), (b'Camarerao', b'Camarera(o)'), (b'Luc_social', b'Luc. social'), (b'Ejecutivoa_Bancaria', b'Ejecutivo(a) Bancaria'), (b'Otroa', b'Otros(as)')], max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('telef_cel', models.IntegerField()),
                ('telef_res', models.IntegerField()),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id_vivienda', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo_vivien', models.CharField(choices=[('Casa', 'Casa'), ('Quinta', 'Quinta'), ('Apartamento', 'Apartamento'), ('Anexo', 'Anexo'), ('Vivienda Rural', 'Vivienda Rural'), ('Otra', 'Otra')], default=6, max_length=15)),
                ('zona', models.CharField(max_length=100, verbose_name='Zona')),
                ('agua', models.BooleanField(verbose_name='Agua')),
                ('aseo_urbano', models.BooleanField(verbose_name='Aseo Urbano')),
                ('cloacas', models.BooleanField(verbose_name='Cloacas')),
                ('internet', models.BooleanField(verbose_name='Internet')),
                ('nevera', models.BooleanField(verbose_name='Nevera')),
                ('cocina', models.BooleanField(verbose_name='Cocina')),
                ('lavadora', models.BooleanField(verbose_name='Lavadora')),
                ('secadora', models.BooleanField(verbose_name='Secadora')),
                ('computadora', models.BooleanField(verbose_name='Computadora')),
                ('celular', models.BooleanField(verbose_name='Celular')),
                ('telefono_fijo', models.BooleanField(verbose_name='Telefono Fijo')),
                ('calentador_de_agua', models.BooleanField(verbose_name='Calentador De Agua')),
                ('habitacione', models.IntegerField()),
                ('num_habitan', models.IntegerField()),
                ('num_bano', models.IntegerField()),
                ('habitan_tra', models.IntegerField()),
                ('habitan_apo', models.IntegerField()),
                ('mon_apr_men', models.IntegerField()),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='percep_repre',
            name='cedula_repres',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Representante'),
        ),
    ]
