# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nacionalidad', models.CharField(choices=[('V', 'V'), ('E', 'E')], default=2, max_length=5, verbose_name='Nacionalidad*')),
                ('cedula_alumno', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Cedula*')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Primer Nombre*')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer Apellido*')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('sexo_alumno', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=2, max_length=10, verbose_name='Sexo*')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha De Nacimiento*')),
                ('lugar_nacimiento', models.CharField(max_length=100, verbose_name='Lugar De Nacimiento*')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institucion*')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entid_feder', models.CharField(choices=[('Distrito Capital', 'Distrito Capital'), ('Miranda', 'Miranda'), ('Aragua', 'Aragua'), ('Monagas', 'Monagas'), ('Falcon', 'Falcon'), ('Carabobo', 'Carabobo'), ('Nueva Esparta', 'Nueva Esparta'), ('Anzoategui', 'Anzoategui'), ('Vargas', 'Vargas'), ('Zulia', 'Zulia'), ('Bolivar', 'Bolivar'), ('Lara', 'Lara'), ('Merida', 'Merida'), ('Tachira', 'Tachira'), ('Guarico', 'Guarico'), ('Cojedes', 'Cojedes'), ('Trujillo', 'Trujillo'), ('Barinas', 'Barinas'), ('Sucre', 'Sucre'), ('Yaracuy', 'Yaracuy'), ('Portuguesa', 'Portuguesa'), ('Delta Amacuro', 'Delta Amacuro'), ('Apure', 'Apure'), ('Amazonas', 'Amazonas')], default=0, max_length=20, verbose_name='Entidad Federal*')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad*')),
                ('parroquia', models.CharField(max_length=100, verbose_name='Parroquia*')),
                ('sector', models.CharField(max_length=100, verbose_name='Sector*')),
                ('barri_urban', models.CharField(max_length=250, verbose_name='Barrio/Urbanizacion*')),
                ('calle_avend', models.CharField(max_length=150, verbose_name='Calle/Avenida*')),
                ('apt_casa', models.CharField(max_length=100, verbose_name='Apartamento/Casa*')),
                ('cedula_alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='EducaAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_e', models.CharField(choices=[('Nivel Uno', 'Nivel Uno'), ('Nivel Dos', 'Nivel Dos'), ('Nivel Tres', 'Nivel Tres'), ('Primer Grado', 'Primer Grado'), ('Segundo Grado', 'Segundo Grado'), ('Tercer Grado', 'Tercer Grado'), ('Cuarto Grado', 'Cuarto Grado'), ('Quinto Grado', 'Quinto Grado'), ('Sexto Grado', 'Sexto Grado'), ('Educacion Media Uno', 'Educacion Media Uno'), ('Educacion Media Dos', 'Educacion Media Dos'), ('Primer A\xf1o', 'Primer A\xf1o'), ('Segundo A\xf1o', 'Segundo A\xf1o'), ('Tercer A\xf1o', 'Tercer A\xf1o'), ('Cuarto A\xf1o', 'Cuarto A\xf1o'), ('Quinto A\xf1o', 'Quinto A\xf1o'), ('Sexto A\xf1o', 'Sexto A\xf1o')], max_length=20, verbose_name='Nivel Educativo*')),
                ('curso', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula_alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='EducaMusi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progama_orque', models.CharField(blank=True, max_length=100, null=True, verbose_name='Programas Orquestales Y/O Corales En Los Que Participa')),
                ('instru_princi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instrumento Principal')),
                ('prof_clas_ind', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesor De Clase Individial')),
                ('instru_secund', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instrumento Secundario')),
                ('prof_clas_sec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesor De Clase Individial')),
                ('academ_catedr', models.BooleanField(default=False, verbose_name='El Alumno Recibe Clases En Una Academia O Catedra Nacional?')),
                ('nombr_academi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escriba El Nombre De La Catedra Nacional En La Cual Cursa Estudios')),
                ('clas_acad_cate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ha Sido Selecionado Para Pertenecer A Una Orquesta/Coro Nacional?')),
                ('nom_aca_cate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ha Sido Selecionado Para Pertenecer A Una Orquesta/Coro Regional?')),
                ('inst_espc_mus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cursa Estudios En Una Institucion Especializada En Musica?')),
                ('bec_est_esp', models.BooleanField(default=False, verbose_name='Recibe Alguna Beca O Ayuda Para Cursar Estudios Especializados En Musica?')),
                ('estu_cur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Que Estudios Cursa?')),
                ('inst_empr_bec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Que Institucion O Empresa Otorga La Beca')),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre De La Empresa')),
                ('nombre_jefe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jefe De La Empresa')),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_familia', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Cedula Del Familiar*')),
                ('nombre_familia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Del Familiar*')),
                ('apelli_familia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Del Familiar*')),
                ('ocupacion_f', models.CharField(blank=True, choices=[(b'', b'---------'), (b'Comerciante', b'Comerciante'), (b'Barbero', b'Barbero'), (b'Estudiante', b'Estudiante'), (b'Empleadoa', b'Empleado(a)'), (b'Jubiladoa', b'Jubilado(a)'), (b'Tecnico', b'Tecnico'), (b'Pensionadoa', b'Pensionado(a)'), (b'Obreroa', b'Obrero(a)'), (b'Educadora', b'Educador(a)'), (b'Pastora', b'Pastor(a)'), (b'Herrero', b'Herrero'), (b'Maternal', b'Maternal'), (b'Soldador', b'Soldador'), (b'Estilita', b'Estilita'), (b'Manicurista', b'Manicurista'), (b'Amao_de_casa', b'Ama(o) de casa'), (b'Nutricionista', b'Nutricionista'), (b'Obreroa_Educacional', b'Obrero(a) Educacional'), (b'Contador', b'Contador'), (b'Cocineroa', b'Cocinero(a)'), (b'Policia', b'Policia'), (b'Administradorar', b'Administrador(ar)'), (b'Promotora_Socia', b'Promotor(a) Social'), (b'Docente', b'Docente'), (b'Custodio', b'Custodio'), (b'Pencionadoa', b'Pencionado(a)'), (b'Mecanico', b'Mecanico'), (b'Abogadoa', b'Abogado(a)'), (b'Chofer', b'Chofer'), (b'Empleadoa_Publico', b'Empleado(a) Publico'), (b'Laboratorista', b'Laboratorista'), (b'Peluqueroa', b'Peluquero(a)'), (b'Educadora', b'Educador(a)'), (b'Agricultora', b'Agricultor(a)'), (b'TSU', b'TSU'), (b'Enfermeroa', b'Enfermero(a)'), (b'Carpinteroa', b'Carpintero(a)'), (b'Ambientalista', b'Ambientalista'), (b'Militar', b'Militar'), (b'Albanil', b'Alba\xc3\xb1il'), (b'Secretariao', b'Secretaria(o)'), (b'Deportista', b'Deportista'), (b'Vigilante', b'Vigilante'), (b'Costurera', b'Costurera'), (b'Discapacidad', b'Discapacidad'), (b'Camarerao', b'Camarera(o)'), (b'Luc_social', b'Luc. social'), (b'Ejecutivoa_Bancaria', b'Ejecutivo(a) Bancaria'), (b'Otroa', b'Otros(as)')], max_length=100, null=True, verbose_name='Ocupacion*')),
                ('profesion_f', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesion')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion*')),
                ('telef_cel_f', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono Celular*')),
                ('telef_res_f', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono Residencial')),
                ('vive', models.BooleanField(default=False, verbose_name='Vive Con El Alumno?*')),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='PercepNino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_sien_bie', models.BooleanField(default=False, verbose_name='Me Siento Bien')),
                ('m_sien_seg', models.BooleanField(default=False, verbose_name='Me Siento Seguro')),
                ('sien_mejo', models.BooleanField(default=False, verbose_name='Siento Que He Mejorado Como Ser Humano')),
                ('mas_apre_com', models.BooleanField(default=False, verbose_name='Soy Mas Apreciado En La Comunidad')),
                ('m_sien_cap', models.BooleanField(default=False, verbose_name='Me Siento Cansado')),
                ('m_sien_mot', models.BooleanField(default=False, verbose_name='Me Siento Desmotivado')),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='PercepRepre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup_fam_reco_com', models.BooleanField(default=False, verbose_name='Como Grupo Familiar Somos Reconocidos En La Comunidad (Nos Respetan Mas)')),
                ('asis_nin_act_mus', models.BooleanField(default=False, verbose_name='La Asistencia De Mis Ni\xf1os Al La Actividad Musical, Mejoro Las Relaciones Familiares')),
                ('prac_mus_ent_eco', models.BooleanField(default=False, verbose_name='La Practica Musical Produce Una Entrada Economica Mas En El Grupo Familiar')),
                ('viv_mej', models.BooleanField(default=False, verbose_name='Ahora Vivo Mejor')),
                ('otra_razon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otra Razon')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('cedula_repres', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Cedula Representante*')),
                ('nombre_repres', models.CharField(max_length=50, verbose_name='Nombre Del Representante*')),
                ('apelli_repres', models.CharField(max_length=50, verbose_name='Apellido Del Representante*')),
                ('ocupacion', models.CharField(choices=[(b'', b'---------'), (b'Comerciante', b'Comerciante'), (b'Barbero', b'Barbero'), (b'Estudiante', b'Estudiante'), (b'Empleadoa', b'Empleado(a)'), (b'Jubiladoa', b'Jubilado(a)'), (b'Tecnico', b'Tecnico'), (b'Pensionadoa', b'Pensionado(a)'), (b'Obreroa', b'Obrero(a)'), (b'Educadora', b'Educador(a)'), (b'Pastora', b'Pastor(a)'), (b'Herrero', b'Herrero'), (b'Maternal', b'Maternal'), (b'Soldador', b'Soldador'), (b'Estilita', b'Estilita'), (b'Manicurista', b'Manicurista'), (b'Amao_de_casa', b'Ama(o) de casa'), (b'Nutricionista', b'Nutricionista'), (b'Obreroa_Educacional', b'Obrero(a) Educacional'), (b'Contador', b'Contador'), (b'Cocineroa', b'Cocinero(a)'), (b'Policia', b'Policia'), (b'Administradorar', b'Administrador(ar)'), (b'Promotora_Socia', b'Promotor(a) Social'), (b'Docente', b'Docente'), (b'Custodio', b'Custodio'), (b'Pencionadoa', b'Pencionado(a)'), (b'Mecanico', b'Mecanico'), (b'Abogadoa', b'Abogado(a)'), (b'Chofer', b'Chofer'), (b'Empleadoa_Publico', b'Empleado(a) Publico'), (b'Laboratorista', b'Laboratorista'), (b'Peluqueroa', b'Peluquero(a)'), (b'Educadora', b'Educador(a)'), (b'Agricultora', b'Agricultor(a)'), (b'TSU', b'TSU'), (b'Enfermeroa', b'Enfermero(a)'), (b'Carpinteroa', b'Carpintero(a)'), (b'Ambientalista', b'Ambientalista'), (b'Militar', b'Militar'), (b'Albanil', b'Alba\xc3\xb1il'), (b'Secretariao', b'Secretaria(o)'), (b'Deportista', b'Deportista'), (b'Vigilante', b'Vigilante'), (b'Costurera', b'Costurera'), (b'Discapacidad', b'Discapacidad'), (b'Camarerao', b'Camarera(o)'), (b'Luc_social', b'Luc. social'), (b'Ejecutivoa_Bancaria', b'Ejecutivo(a) Bancaria'), (b'Otroa', b'Otros(as)')], max_length=100, verbose_name='Ocupacion*')),
                ('profesion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesion')),
                ('telef_cel', models.CharField(blank=True, max_length=11, verbose_name='Telefono Celular*')),
                ('telef_res', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono Residencial')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion*')),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vivien', models.CharField(choices=[('Casa', 'Casa'), ('Quinta', 'Quinta'), ('Apartamento', 'Apartamento'), ('Anexo', 'Anexo'), ('Vivienda Rural', 'Vivienda Rural'), ('Otra', 'Otra')], default=6, max_length=15, verbose_name='Tipo De Vivienda')),
                ('zona', models.CharField(max_length=100, verbose_name='Zona')),
                ('agua', models.BooleanField(default=False, verbose_name='Agua')),
                ('aseo_urbano', models.BooleanField(default=False, verbose_name='Aseo Urbano')),
                ('cloacas', models.BooleanField(default=False, verbose_name='Cloacas')),
                ('telefono_fijo', models.BooleanField(default=False, verbose_name='Telefono Fijo')),
                ('internet', models.BooleanField(default=False, verbose_name='Internet')),
                ('nevera', models.BooleanField(default=False, verbose_name='Nevera')),
                ('cocina', models.BooleanField(default=False, verbose_name='Cocina')),
                ('lavadora', models.BooleanField(default=False, verbose_name='Lavadora')),
                ('secadora', models.BooleanField(default=False, verbose_name='Secadora')),
                ('computadora', models.BooleanField(default=False, verbose_name='Computadora')),
                ('celular', models.BooleanField(default=False, verbose_name='Celular')),
                ('calentador_de_agua', models.BooleanField(default=False, verbose_name='Calentador De Agua')),
                ('habitacione', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero De Habitaciones En La Vivienda')),
                ('num_habitan', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero De Habitantes En La Vivienda')),
                ('num_bano', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero De Ba\xf1os En La Vivienda')),
                ('habitan_tra', models.CharField(blank=True, max_length=10, null=True, verbose_name='Habitantes Que Trabajan')),
                ('habitan_apo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Habitantes Que Aportan')),
                ('mon_apr_men', models.CharField(blank=True, max_length=1000000000, null=True, verbose_name='Monto Aproximado De Ingresos Total Mensual En El Hogar(Bs)')),
                ('cedula_alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='perceprepre',
            name='cedula_repres',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Representante'),
        ),
    ]
