# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_remove_representante_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion*'),
        ),
    ]
