# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='instrumento',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
    ]
