# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-26 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, default='C\xe9dula', max_length=40, verbose_name='username'),
        ),
    ]
