# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluado',
            name='evaluado',
        ),
        migrations.RemoveField(
            model_name='evaluado',
            name='status',
        ),
        migrations.AddField(
            model_name='evaluado',
            name='examen',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado')], default=2, max_length=10),
        ),
    ]
