# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignados',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
