# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='apellido_profesor',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='asignacion',
            field=models.CharField(choices=[('Programa Alma Llanera', 'Programa Alma Llanera'), ('Arpa Clasica', 'Arpa Clasica'), ('Orquesta Infantil', 'Orquesta Infantil'), ('Oboe', 'Oboe'), ('Cuatro', 'Cuatro'), ('Percusion', 'Percusion'), ('Violincello', 'Violincello'), ('Trombon', 'Trombon'), ('Coro/Lenguaje Musical', 'Coro/Lenguaje Musical'), ('Flauta/Lenguaje Musical', 'Flauta/Lenguaje Musical'), ('Corno', 'Corno'), ('Guitarra', 'Guitarra'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Viola/Lenguaje Musical', 'Viola/Lenguaje Musical'), ('Flauta', 'Flauta'), ('Clarinete', 'Clarinete'), ('Tuba', 'Tuba'), ('Trompeta/Lenguaje Musical', 'Trompeta/Lenguaje Musical'), ('Contrabajo', 'Contrabajo'), ('Pianista', 'Pianista')], default=0, max_length=40, verbose_name='Asignacion'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cedula_profesor',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre_profesor',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
