# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_auto_20180128_1937'),
        ('profesor', '0002_auto_20180308_0816'),
    ]

    operations = [
    ]
